version: '3.7'

services:
  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    ports:
      - "8081:8081"  # Flink UI
      - "9260:9249"  # Prometheus metrics port
    networks:
      - flink-network
    volumes:
      - ./flink-conf.yaml:/opt/flink/conf/flink-conf.yaml  # Mount the Flink configuration file
      - /c/Users/User/Downloads/DSPBench-master/DSPBench-master/dspbench-flink/data/books.dat:/opt/flink/book.dat  # Mount books.dat file

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - flink-network
    volumes:
      - ./flink-conf.yaml:/opt/flink/conf/flink-conf.yaml  # Mount the Flink configuration file
      - /c/Users/User/Downloads/DSPBench-master/DSPBench-master/dspbench-flink/data/books.dat:/opt/flink/book.dat  # Mount books.dat file
    depends_on:
      - jobmanager
    scale: 3

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount the Prometheus configuration file
    ports:
      - "9090:9090"
    networks:
      - flink-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - flink-network
    depends_on:
      - prometheus

networks:
  flink-network:
    driver: bridge
