global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "flink-task-manager"
    dns_sd_configs:
      - names:
          - 'taskmanager'
        refresh_interval: 10s
        type: 'A'
        port: 9250
    metrics_path: /
  - job_name: "flink-job-manger"
    static_configs:
      - targets: [ "jobmanager:9250" ]
    metrics_path: /