version: '3.7'

services:
  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    ports:
      - "8081:8081"  # Flink UI
      - "9260:9249"  # Prometheus metrics port
    networks:
      - flink-network
    volumes:
      - ./flink-conf.yaml:/opt/flink/conf/flink-conf.yaml  # Mount the Flink configuration file
      - ./books.dat:/opt/flink/book.dat  # Mount books.dat file

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - flink-network
    volumes:
      - ./flink-conf.yaml:/opt/flink/conf/flink-conf.yaml  # Mount the Flink configuration file
      - ./books.dat:/opt/flink/book.dat  # Mount books.dat file
    depends_on:
      - jobmanager
    scale: 3

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount the Prometheus configuration file
    ports:
      - "9090:9090"
    networks:
      - flink-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - flink-network
    depends_on:
      - prometheus

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - flink-network

  kafka:
    image: confluentinc/cp-kafka:3.3.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - flink-network
    volumes:
      - ../textokafka/target/untitled-1.0-SNAPSHOT.jar:/home/untitled-1.0-SNAPSHOT.jar
      - ./books.dat:/home/book.dat

networks:
  flink-network:
    driver: bridge
